# Google App Engine configuration for BIA Trading Platform
runtime: nodejs18

instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.7

env_variables:
  NODE_ENV: production
  
# Health check configuration
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# VPC configuration (optional)
# vpc_access_connector:
#   name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME

# Network settings
network:
  forwarded_ports:
    - 4173

# Security settings
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301