// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqzmvpihhbvakfztbvdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xem12cGloaGJ2YWtmenRidmRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTA2NjAsImV4cCI6MjA2NzcyNjY2MH0.x7n5Rl8237zaQHsVBYUvn1RKINihcZTGdOr8ZGFK7wY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});